version: '3.8'

services:

  # ✅ PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cjfemfwk77!
      POSTGRES_DB: popoworld
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-net

#  # ✅ MongoDB
#  mongodb:
#    image: mongo:5.0
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db
#    networks:
#      - backend-net

  # ✅ Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend-net

  # ✅ Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend-net

#  # ✅ Elasticsearch
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
#    networks:
#      - backend-net

#  # ✅ Kibana (optional)
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.11.1
#    container_name: kibana
#    depends_on:
#      - elasticsearch
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    networks:
#      - backend-net

  # ✅ Spring Boot Backend
  spring-boot-app:
    build:
      context: ./back-repo
    container_name: spring-boot-app
    depends_on:
      - postgres
      - kafka
      - mongodb
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/popoworld
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: cjfemfwk77!
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - backend-net

volumes:
  postgres-data:
  mongo-data:

networks:
  backend-net:
